# Basic server properties
server:
  port: ${NOTIFICATION_PORT:9005}

# Basic spring properties
spring:
  # Application
  application:
    name: ${NOTIFICATION_APPLICATION_NAME:notification-service}

# Basic actuator properties
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:*}
  endpoint:
    health:
      show-details: ${ACTUATOR_HEALTH_SHOW_DETAILS:always}